### ISSUE TITLE
what is the difference between findcut(findcutnum) and findcutCox(findcutnumCox)?

### ISSUE THREAD

**Issue by ayueme** [paytonyau/BestSurvivalCuts#2]
Hello,  Thanks for your great work.
Sorry to bother you, based on your vignette, however, I can't figure out the difference between findcut(findcutnum) and findcutCox(findcutnumCox). It seems the same. 
Could you please make a detailed explanation about these two functions?
Thank you very much.

**Comment by paytonyau** [comment]
Hello ayueme, 

The function `findcut(findcutnum)` is based on the Akaike Information Criterion (AIC) model, while `findcutCox(findcutnumCox)` uses the Cox model. Please note that there may be some issues with using `findcut(findcutnum)`, most likely related to the parameters for `segment` and `nmin`. I have not had time to thoroughly test `findcutCox(findcutnumCox)`. 

Payton

**Comment by paytonyau** [comment]
Hello ayueme, 

The function `findcut(findcutnum)` is based on the Akaike Information Criterion (AIC) model, while `findcutCox(findcutnumCox)` uses the Cox model. Please note that there may be some issues with using `findcut(findcutnum)`, most likely related to the parameters for `segment` and `nmin`. I have not had time to thoroughly test `findcutCox(findcutnumCox)`. 

Payton
